// <auto-generated />
using System;
using MHC.Invoicing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MHC.Invoicing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MhcDbContext))]
    [Migration("20260722235510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ms");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details_json");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<long>("OccurredAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at_utc_ms");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_name");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "OccurredAtUtcMs")
                        .HasFilter("invoice_id IS NOT NULL");

                    b.HasIndex("OccurredAtUtcMs", "Id")
                        .IsDescending(true, false);

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.CatalogItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ms");

                    b.Property<long>("DefaultUnitPriceHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_unit_price_halalah");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_arabic");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_english");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("SearchNameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("search_name_arabic");

                    b.Property<string>("SearchNameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("search_name_english");

                    b.Property<string>("SearchSku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("search_sku");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ms");

                    b.Property<int>("VatCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_category");

                    b.HasKey("Id");

                    b.HasIndex("SearchSku")
                        .IsUnique()
                        .HasFilter("is_archived = 0 AND search_sku <> ''");

                    b.HasIndex("IsArchived", "SearchNameArabic", "Id");

                    b.HasIndex("IsArchived", "SearchNameEnglish", "Id");

                    b.HasIndex("IsArchived", "SearchSku", "Id");

                    b.ToTable("catalog_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_items_archived", "is_archived IN (0, 1)");

                            t.HasCheckConstraint("ck_catalog_items_price", "default_unit_price_halalah >= 0");

                            t.HasCheckConstraint("ck_catalog_items_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_catalog_items_updated", "updated_at_utc_ms >= created_at_utc_ms");

                            t.HasCheckConstraint("ck_catalog_items_vat", "vat_category IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.CompanyProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("CommercialRegistration")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("commercial_registration");

                    b.Property<long>("CreatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ms");

                    b.Property<int>("DefaultPaymentMethod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_payment_method");

                    b.Property<byte[]>("LogoBytes")
                        .HasColumnType("BLOB")
                        .HasColumnName("logo_bytes");

                    b.Property<string>("LogoMimeType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_mime_type");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_arabic");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_english");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_name");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ms");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_number");

                    b.HasKey("Id");

                    b.ToTable("company_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_company_profiles_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_company_profiles_singleton", "id = 1");

                            t.HasCheckConstraint("ck_company_profiles_updated", "updated_at_utc_ms >= created_at_utc_ms");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("CommercialRegistration")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("commercial_registration");

                    b.Property<long>("CreatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ms");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_archived");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_arabic");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_english");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("SearchNameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("search_name_arabic");

                    b.Property<string>("SearchNameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("search_name_english");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ms");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("vat_number");

                    b.HasKey("Id");

                    b.HasIndex("CommercialRegistration")
                        .HasFilter("commercial_registration IS NOT NULL");

                    b.HasIndex("VatNumber")
                        .HasFilter("vat_number IS NOT NULL");

                    b.HasIndex("IsArchived", "SearchNameArabic", "Id");

                    b.HasIndex("IsArchived", "SearchNameEnglish", "Id");

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("ck_customers_archived", "is_archived IN (0, 1)");

                            t.HasCheckConstraint("ck_customers_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_customers_updated", "updated_at_utc_ms >= created_at_utc_ms");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDocumentEntity", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_length");

                    b.Property<long>("CreatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ms");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<byte[]>("PdfBytes")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("pdf_bytes");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("sha256");

                    b.HasKey("InvoiceId");

                    b.ToTable("invoice_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_documents_hash", "length(sha256) = 32");

                            t.HasCheckConstraint("ck_invoice_documents_length", "byte_length > 0 AND byte_length = length(pdf_bytes)");

                            t.HasCheckConstraint("ck_invoice_documents_mime", "mime_type = 'application/pdf'");

                            t.HasCheckConstraint("ck_invoice_documents_pdf", "length(pdf_bytes) > 0");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<long>("CreatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc_ms");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_address");

                    b.Property<string>("CustomerCommercialRegistration")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_commercial_registration");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_name_arabic");

                    b.Property<string>("CustomerNameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_name_english");

                    b.Property<string>("CustomerVatNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_vat_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OriginalInvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_invoice_id");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_method");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<bool>("ShowNotes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_notes");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc_ms");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasFilter("customer_id IS NOT NULL");

                    b.HasIndex("OriginalInvoiceId")
                        .HasFilter("original_invoice_id IS NOT NULL");

                    b.HasIndex("UpdatedAtUtcMs", "Id")
                        .IsDescending(true, false);

                    b.ToTable("invoice_drafts", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_drafts_original", "(document_type = 1 AND original_invoice_id IS NULL) OR (document_type = 2 AND original_invoice_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_invoice_drafts_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_invoice_drafts_type", "document_type IN (1, 2)");

                            t.HasCheckConstraint("ck_invoice_drafts_updated", "updated_at_utc_ms >= created_at_utc_ms");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDraftLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("catalog_item_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT")
                        .HasColumnName("draft_id");

                    b.Property<Guid?>("OriginalInvoiceLineId")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_invoice_line_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<long>("QuantityMilliunits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_milliunits");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<string>("TaxExemptionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_exemption_reason");

                    b.Property<string>("TaxExemptionReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_exemption_reason_code");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<long>("UnitPriceHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price_halalah");

                    b.Property<int>("VatCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_category");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("OriginalInvoiceLineId")
                        .HasFilter("original_invoice_line_id IS NOT NULL");

                    b.HasIndex("DraftId", "Position")
                        .IsUnique();

                    b.ToTable("invoice_draft_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_draft_lines_position", "position >= 0");

                            t.HasCheckConstraint("ck_invoice_draft_lines_price", "unit_price_halalah >= 0");

                            t.HasCheckConstraint("ck_invoice_draft_lines_quantity", "quantity_milliunits BETWEEN 1 AND 1000000000");

                            t.HasCheckConstraint("ck_invoice_draft_lines_vat", "vat_category IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BusinessDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("business_date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_address");

                    b.Property<string>("CustomerCommercialRegistration")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_commercial_registration");

                    b.Property<string>("CustomerNameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_name_arabic");

                    b.Property<string>("CustomerNameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_name_english");

                    b.Property<string>("CustomerSearchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_search_name");

                    b.Property<string>("CustomerVatNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_vat_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_type");

                    b.Property<long>("GrandTotalHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grand_total_halalah");

                    b.Property<int>("IssuanceYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issuance_year");

                    b.Property<string>("IssuedAtSaudiLocal")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at_saudi_local");

                    b.Property<long>("IssuedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued_at_utc_ms");

                    b.Property<int>("IssuedSaudiOffsetMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued_saudi_offset_minutes");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_name");

                    b.Property<Guid?>("OriginalInvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_invoice_id");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_number");

                    b.Property<string>("SellerAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("seller_address");

                    b.Property<string>("SellerBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("seller_branch");

                    b.Property<string>("SellerCommercialRegistration")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("seller_commercial_registration");

                    b.Property<byte[]>("SellerLogoBytes")
                        .HasColumnType("BLOB")
                        .HasColumnName("seller_logo_bytes");

                    b.Property<string>("SellerLogoMimeType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("seller_logo_mime_type");

                    b.Property<string>("SellerNameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("seller_name_arabic");

                    b.Property<string>("SellerNameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("seller_name_english");

                    b.Property<string>("SellerVatNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("seller_vat_number");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<bool>("ShowNotes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_notes");

                    b.Property<Guid?>("SourceCustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_customer_id");

                    b.Property<long>("SubtotalHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subtotal_halalah");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("VatHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_halalah");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCommercialRegistration")
                        .HasFilter("customer_commercial_registration IS NOT NULL");

                    b.HasIndex("CustomerVatNumber")
                        .HasFilter("customer_vat_number IS NOT NULL");

                    b.HasIndex("OriginalInvoiceId")
                        .HasFilter("original_invoice_id IS NOT NULL");

                    b.HasIndex("PublicNumber")
                        .IsUnique();

                    b.HasIndex("SourceCustomerId");

                    b.HasIndex("BusinessDate", "Id")
                        .IsDescending(true, false);

                    b.HasIndex("CustomerSearchName", "Id");

                    b.HasIndex("DocumentType", "IssuedAtUtcMs")
                        .IsDescending(false, true);

                    b.HasIndex("IssuanceYear", "Sequence")
                        .IsUnique();

                    b.HasIndex("IssuedAtUtcMs", "Id")
                        .IsDescending(true, false);

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_currency", "currency = 'SAR'");

                            t.HasCheckConstraint("ck_invoices_offset", "issued_saudi_offset_minutes = 180");

                            t.HasCheckConstraint("ck_invoices_original", "(document_type = 1 AND original_invoice_id IS NULL) OR (document_type = 2 AND original_invoice_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_invoices_sequence", "sequence >= 100");

                            t.HasCheckConstraint("ck_invoices_totals", "grand_total_halalah = subtotal_halalah + vat_halalah");

                            t.HasCheckConstraint("ck_invoices_type", "document_type IN (1, 2)");

                            t.HasCheckConstraint("ck_invoices_year", "issuance_year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("GrossHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gross_halalah");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<long>("NetHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("net_halalah");

                    b.Property<Guid?>("OriginalInvoiceLineId")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_invoice_line_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<long>("QuantityMilliunits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_milliunits");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sku");

                    b.Property<Guid?>("SourceCatalogItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_catalog_item_id");

                    b.Property<string>("TaxExemptionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_exemption_reason");

                    b.Property<string>("TaxExemptionReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_exemption_reason_code");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<long>("UnitPriceHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price_halalah");

                    b.Property<int>("VatCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_category");

                    b.Property<long>("VatHalalah")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vat_halalah");

                    b.HasKey("Id");

                    b.HasIndex("OriginalInvoiceLineId")
                        .HasFilter("original_invoice_line_id IS NOT NULL");

                    b.HasIndex("SourceCatalogItemId");

                    b.HasIndex("InvoiceId", "Position")
                        .IsUnique();

                    b.ToTable("invoice_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_lines_gross", "gross_halalah = net_halalah + vat_halalah");

                            t.HasCheckConstraint("ck_invoice_lines_net", "net_halalah >= 0");

                            t.HasCheckConstraint("ck_invoice_lines_position", "position >= 0");

                            t.HasCheckConstraint("ck_invoice_lines_price", "unit_price_halalah >= 0");

                            t.HasCheckConstraint("ck_invoice_lines_quantity", "quantity_milliunits BETWEEN 1 AND 1000000000");

                            t.HasCheckConstraint("ck_invoice_lines_vat", "vat_halalah >= 0");

                            t.HasCheckConstraint("ck_invoice_lines_vat_category", "vat_category IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceSequenceEntity", b =>
                {
                    b.Property<int>("IssuanceYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("issuance_year");

                    b.Property<int>("NextValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_value");

                    b.HasKey("IssuanceYear");

                    b.ToTable("invoice_sequences", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_sequences_next", "next_value >= 100");

                            t.HasCheckConstraint("ck_invoice_sequences_year", "issuance_year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceVoidEntity", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_name");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<long>("VoidedAtUtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voided_at_utc_ms");

                    b.HasKey("InvoiceId");

                    b.ToTable("invoice_voids", (string)null);
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDocumentEntity", b =>
                {
                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithOne("Document")
                        .HasForeignKey("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDocumentEntity", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDraftEntity", b =>
                {
                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.CustomerEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginalInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDraftLineEntity", b =>
                {
                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.CatalogItemEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDraftEntity", "Draft")
                        .WithMany("Lines")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceLineEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginalInvoiceLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginalInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.CustomerEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceLineEntity", b =>
                {
                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceLineEntity", null)
                        .WithMany()
                        .HasForeignKey("OriginalInvoiceLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.CatalogItemEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceVoidEntity", b =>
                {
                    b.HasOne("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithOne("Void")
                        .HasForeignKey("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceVoidEntity", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceDraftEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MHC.Invoicing.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("Document");

                    b.Navigation("Lines");

                    b.Navigation("Void");
                });
#pragma warning restore 612, 618
        }
    }
}
