<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\src\MHC.Invoicing.App\MHC.Invoicing.App.csproj" />
    <ProjectReference Include="..\..\src\MHC.Invoicing.Application\MHC.Invoicing.Application.csproj" />
    <ProjectReference Include="..\..\src\MHC.Invoicing.Domain\MHC.Invoicing.Domain.csproj" />
  </ItemGroup>

</Project>